# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
date_format: "ordinal"
name: 有無教義
title: 有無教義
subtitle:
description: GloomyGhost | MosquitoSeal 's GitHub Small Repo
keywords: GloomyGhost MosquitoSea GitHub
favicon: /assets/images/logo.png
encoding: "utf-8"

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
auto: true
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji

collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: UMUISM/UMUISM.GITHUB.IO

